const FILTER_SHOW_ALL = 'FILTER_SHOW_ALL';
const FILTER_MEMORIZED = 'FILTER_MEMORIZED';
const FILTER_NEED_PRACTICE = 'FILTER_NEED_PRACTICE';

const TOGGLE_SHOW_HIDE = 'TOGGLE_SHOW_HIDE';
const TOGGLE_MEMORIZED_FORGET = 'TOGGLE_MEMORIZED_FORGET';

const SHOW_FORM_BUTTON = 'SHOW_FORM_BUTTON';

const ADD_NEW_WORD = 'ADD_NEW_WORD';

export {
    FILTER_MEMORIZED, 
    FILTER_SHOW_ALL, 
    FILTER_NEED_PRACTICE, 
    TOGGLE_SHOW_HIDE, 
    TOGGLE_MEMORIZED_FORGET,
    SHOW_FORM_BUTTON,
    ADD_NEW_WORD

};